### ISSUE TITLE
Binds don't save

### ISSUE THREAD

**Issue by Katatje** [Katatje/Dream#7]

**Comment by yagel15637** [comment]
@Katatje I could work on something if you're not on it already, also settings don't save either so note that when working on binds

**Comment by Katatje** [comment]
I have been quite busy lately but I'll try to work on it tomorrow.

**Comment by yagel15637** [comment]
that's cool, good luck

**Comment by Katatje** [comment]
Thanks

**Comment by Ihackedsctrach** [comment]
Is it just not saving or is it like opfern where it just doesn’t save

**Comment by Ihackedsctrach** [comment]
*i meant like the client saving nothing

**Comment by Katatje** [comment]
Nah I forgot to code the bind saving parts lol

**Comment by Ihackedsctrach** [comment]
KEK
