### ISSUE TITLE
ca thingy idk if it works but i dont wanna do work:^)

### ISSUE THREAD

**Issue by Ihackedsctrach** [Katatje/Dream#9]
to find it go to my git then just download Dream-

**Comment by Katatje** [comment]
lol wdym

**Comment by Ihackedsctrach** [comment]
Added a ca and it came with 0 problems lol

**Comment by Katatje** [comment]
Can you make a pull request?

**Comment by Ihackedsctrach** [comment]
im currently in class ill do it when im on my pc

**Comment by KohimaNayagato** [comment]
lol skidded from pepsimod bruhh

**Comment by Ihackedsctrach** [comment]
thats the joke its bassicly a paste but changed the imports and it worked

**Comment by Katatje** [comment]
lol

**Comment by Ihackedsctrach** [comment]
like no shit didnt even change the utils and it built

**Comment by Katatje** [comment]
lmao
